server:
  port: 8082

dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    host: 127.0.0.1
  registry:
    address: zookeeper://127.0.0.1:2181  # zookeeper 注册中心地址
  scan:
    base-packages: org.cxyxh.service